rideshare/rides/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *

urlpatterns = patterns('rideshare.rides.views',
	(r'^$', 'ShowIndex'),
	(r'^addride/$', 'add_ride'),
	(r'^findride/$', 'find_ride'),
	(r'^signup/$', 'add_user'),
)

rideshare/urls.py
from django.conf.urls.defaults import *
import rides.views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    #(r'^rides/', rides.views.index),
    (r'^rides/', include('rideshare.rides.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

rideshare/rides/models.py
# -*- coding: utf-8 -*-
"""mwGm"""

from django.db import models

class User(models.Model):
    fname       = models.CharField(max_length=30)
    lname       = models.CharField(max_length=40)
    uniquename  = models.CharField(max_length=30)
    email       = models.EmailField()
    karma       = models.IntegerField()
    
    def __unicode__(self):
        return self.fname + " " + self.lname
    
    
class Ride(models.Model):
    date        = models.DateField()
    dest        = models.CharField(max_length=30)
    driver      = models.ForeignKey(User)
    space       = models.IntegerField()
    note        = models.CharField(max_length=500)  #any note the driver has
    requested   = models.IntegerField()             #a rough count for popularity

rideshare/rides/forms.py
# -*- coding: utf-8 -*-
"""mwGm"""

from django import forms
from rideshare.rides.models import User

DEST_CHOICES = [
                 ('Ann Arbor', 'Ann Arbor'),
                 ('DTW', 'DTW'),
               ]
class AddUserForm(forms.Form):
    fname       = forms.CharField(max_length=30, label="First Name")
    lname       = forms.CharField(max_length=40, label="Last Name")
    uniquename  = forms.CharField(max_length=30, label="Uniquename")
    email       = forms.EmailField(max_length=30, label="Email")
    
    
    
class AddRideForm(forms.Form):
    date        = forms.DateField()
    dest        = forms.ChoiceField(choices=DEST_CHOICES)
    uniquename  = forms.CharField(max_length=30)
    space       = forms.IntegerField()
    note        = forms.CharField(max_length=500, required=False, widget=forms.Textarea)
    
    def clean_uniquename(self):
        un = self.cleaned_data['uniquename']
        try:
            driver = User.objects.get(uniquename=un)
        except User.DoesNotExist:
            raise forms.ValidationError("Unknown uniquename. Are you registered?")
        return un
        
        
class FindRideForm(forms.Form):
    date        =forms.DateField()
    dest        =forms.ChoiceField(choices=DEST_CHOICES)

    

rideshare/rides/views.py
# -*- coding: utf-8 -*-
# Create your views here.
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.template import Context
from django.shortcuts import render_to_response
from django.template import RequestContext


from rideshare.rides.forms import *
from rideshare.rides.models import *

pages = {	'addride'	:'addride_form.html',
			'signup'	:'adduser_form.html',
			'findride'	:'findride_form.html',
			'showrides' :'showrides.html',
			'index'		:'index.html',
			'signedup'	:'signedup.html',
			'duplicate'	:'duplicate.html',
			'message'   :'message.html'
		}

def ShowIndex(request):
    return render_to_response(pages['index'])

def ShowAlreadySignedUp(user):
    return render_to_response(pages['duplicate'],
        {'fname':user.fname, 'lname':user.lname})
     
def ShowSignedUp(fname):
    return render_to_response(pages['signedup'], 
        {'fname':fname})
        
def ShowMessage(message):
    return render_to_response(pages['message'],
        {'message':message})
        
def ShowRides(date, dest, rides):
    return render_to_response(pages['showrides'],
        {'date':date, 'dest':dest, 'rides':rides})
        
        
        
def add_user(request):
    if request.method == 'POST':
        form = AddUserForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            try:
                user = User.objects.get(uniquename=cd['uniquename'])
                return ShowAlreadySignedUp(user)
            except User.DoesNotExist:
                User.objects.create(fname=cd['fname'], lname=cd['lname'], email=cd['email'],
                                    uniquename=cd['uniquename'], karma=0)
                return ShowSignedUp(cd['fname'])
    else:
        form = AddUserForm(initial={'email':'@umich.edu'})
        
    return render_to_response(pages['signup'], {'form': form})
    
def add_ride(request):
    if request.method == 'POST':
        form = AddRideForm(request.POST)
        if form.is_valid():                     #checks if driver exists. Can be better.
            cd = form.cleaned_data              
            try:
                dude = User.objects.get(uniquename=cd['uniquename'])
                Ride.objects.create(date=cd['date'], dest=cd['dest'], driver=dude,
                                    space=cd['space'],note=cd['note'], requested=0)
                dude.karma = dude.karma + 1
                dude.save()
                return ShowMessage("Your ride is added. Thank you.")
            except:
                return ShowMessage("There was an error with your request.")     #WTF?
    else:
        form = AddRideForm(initial={'date':'MM/DD/YYYY', 'note':'Flight info, time etc.'})
        
    return render_to_response(pages['addride'], {'form':form})
    
def find_ride(request):
    if len(request.GET) > 0:
        form = FindRideForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            rides = Ride.objects.filter(date=cd['date'],dest=cd['dest'])
            return ShowRides(str(cd['date']),cd['dest'], rides)
    else:
        form = FindRideForm(initial={'date':'MM/DD/YYYY'})
    return render_to_response(pages['findride'], {'form':form})

rideshare/templates/addride_form.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<title>CSE Ride Share</title>
	<!--<link rel="stylesheet" href="rides_style.css"> Add when deployed -->
</head>
<body>
	<h3>{% if message.len > 0 %} {{ message }} {% else %} Add ride {% endif %}</h3>
	<div class="main_frame">
        {% if form.errors %}
            <p>
            Please correct the error{{form.errors|pluralize }} below.
            </p>
        {% endif %}
        
        <form action="" method="post">
            <div class="field">
                {{ form.date.errors }}
                <label for="id_date">Date: </label>
                {{ form.date }}
            </div>
 
             <div class="field">
                {{ form.dest.errors }}
                <label for="id_dest">Destination: </label>
                {{ form.dest }}
            </div>
            
             <div class="field">
                {{ form.uniquename.errors }}
                <label for="id_uniquename">Uniquename: </label>
                {{ form.uniquename }}
            </div>   
     
             <div class="field">
                {{ form.space.errors }}
                <label for="id_space">Space: </label>
                {{ form.space }}
            </div> 
            
             <div class="field">
                {{ form.note.errors }}
                <label for="id_note">Notes: </label>
                {{ form.note }}
            </div>             

            <input type="submit" value="Submit">
        </form>
	</div>
	
</body>
</html>

rideshare/templates/adduser_form.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<title>CSE Ride Share</title>
	<!--<link rel="stylesheet" href="rides_style.css"> Add when deployed -->
</head>
<body>
	<h3>{% if message.len > 0 %} {{ message }} {% else %} Sign up {% endif %}</h3>
	<div class="main_frame">
        {% if form.errors %}
            <p>
            Please correct the error{{form.errors|pluralize }} below.
            </p>
        {% endif %}
        
        <form action="" method="post">
            <table>
                {{form.as_table}}
            </table>
            <input type="submit" value="Submit">
	</div>
	
</body>
</html>

rideshare/templates/duplicate.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<title>CSE Ride Share</title>
	<!--<link rel="stylesheet" href="rides_style.css"> Add when deployed -->
</head>
<body>
	<h3>Signed up!</h3>
	<div class='main_frame'>
		<P>User {{fname}} {{lname}} already signed up!
	</div>
</body>
</html>

rideshare/templates/findride_form.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<title>CSE Ride Share</title>
	<!--<link rel="stylesheet" href="rides_style.css"> Add when deployed -->
</head>
<body>
	<h3>{% if message.len > 0 %} {{ message }} {% else %} Find ride {% endif %}</h3>
	<div class="main_frame">
        {% if form.errors %}
            <p>
            Please correct the error{{form.errors|pluralize }} below.
            </p>
        {% endif %}
        
        <form action="" method="get">
            <div class="field">
                {{ form.date.errors }}
                <label for="id_date">Date: </label>
                {{ form.date }}
            </div>
 
             <div class="field">
                {{ form.dest.errors }}
                <label for="id_dest">Destination: </label>
                {{ form.dest }}
            </div>    

            <input type="submit" value="Submit">
	</div>
	
</body>
</html>

rideshare/templates/index.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<title>CSE Ride Share</title>
	<!--<link rel="stylesheet" href="rides_style.css"> Add when deployed -->
</head>
<body>
	<h3>CSE Ride sharing site</h3>
	<div class='main_frame'>
		<div class='nav'>
			<a href="/rides/addride/">Add a trip</a><br>
			<a href="/rides/findride/">Find a trip</a><br>
			<a href="/rides/signup/">Sign-up!</a><br>
		</div>
	</div>
</body>
</html>

rideshare/templates/message.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<title>CSE Ride Share</title>
	<!--<link rel="stylesheet" href="rides_style.css"> Add when deployed -->
</head>
<body>
	<h3>Thank you</h3>
	<div class='main_frame'>
		<P>{{message}}
	</div>
</body>
</html>

rideshare/templates/showrides.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<title>CSE Ride Share</title>
	<!--<link rel="stylesheet" href="rides_style.css"> Add when deployed -->
</head>
<body>
	<h3>{% if message.len > 0 %} {{ message }} {% else %} Rides {% endif %}</h3>
	<div class="main_frame">
        {% if rides %}
            <p>Found {{rides|length}} ride{{ rides|pluralize}}. </p>
            <ul>
                {%for ride in rides %}
                <li>To: {{ride.dest}} On: {{ride.date }} Driver: {{ride.driver.uniquename}} Note: {{ride.note}}</li>
                {%endfor%}
            </ul>
        {% else %}
            <p>Sorry, no rides were found for your date.</P>
        {% endif %}
    </div>
</body>
</html>

rideshare/templates/signedup.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<title>CSE Ride Share</title>
	<!--<link rel="stylesheet" href="rides_style.css"> Add when deployed -->
</head>
<body>
	<h3>Signed up!</h3>
	<div class='main_frame'>
		<P> Thank you for signing up {{fname}}!
	</div>
</body>
</html>